version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/temp:/sandbox-temp
      - ./backend/problems:/problems